# Generated by Django 4.2.15 on 2024-09-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteplo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='servises/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
