# Generated by Django 4.2.15 on 2024-09-15 16:53

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proteplo_app', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='text',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
