# Generated by Django 4.2.15 on 2024-09-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteplo_app', '0003_services_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
