# Generated by Django 4.2.15 on 2024-09-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteplo_app', '0005_gallery_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
    ]
