# Generated by Django 4.2.15 on 2024-09-21 13:05

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proteplo_app', '0009_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=django.db.models.fields.Field.get_db_prep_value),
        ),
    ]
