# Generated by Django 4.2.15 on 2024-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteplo_app', '0012_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='galleries/<function get_image_upload_path at 0x0000023AF8131670>'),
        ),
    ]
