# Generated by Django 4.2.15 on 2024-09-23 18:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proteplo_app', '0014_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('main_text', tinymce.models.HTMLField()),
                ('text', tinymce.models.HTMLField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
