# Generated by Django 4.2.15 on 2024-10-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteplo_app', '0016_gallery_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('review', models.CharField(blank=True, max_length=3000)),
                ('value', models.IntegerField(blank=True)),
            ],
        ),
    ]
